// Auth token we will use to generate a meeting and connect to it
TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlrZXkiOiI4MjM5OWJkYS01NWZjLTQyN2MtYWMxYS1mZTNkZDFmNDA5YTIiLCJwZXJtaXNzaW9ucyI6WyJhbGxvd19qb2luIl0sImlhdCI6MTcwODQxMDAxNywiZXhwIjoxNzIzOTYyMDE3fQ.187Z064DMoMufFrlwPoMrRCp_Rc_ROVxcLRa7wHGacI";
